module.exports = STR => `/${STR
  .replace(/\//g, '\\/')
  .replace(/\$/g, '\\$')
  .replace(/\(/g, '\\(')
  .replace(/\)/g, '\\)')
  .replace(/\*/g, '\\*')
  .replace(/\+/g, '\\+')
  .replace(/\./g, '\\.')
  .replace(/\[/g, '\\[')
  .replace(/\]/g, '\\]')
  .replace(/\\/g, '\\')
  .replace(/\^/g, '\\^')
  .replace(/\{/g, '\\{')
  .replace(/\}/g, '\\}')
  .replace(/\|/g, '\\|')}$/`;
